variables:
- name: subscription 
  

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: ${{ variables.subscription }}
    ScriptType: 'FilePath'
    ScriptPath: 'powershell_test.ps1'
    azurePowerShellVersion: 'LatestVersion'
