parameters:
- name: subscription
  displayName: Name of the azure subscription
  type: string
  

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: ${{ parameters.subscription }}
    ScriptType: 'FilePath'
    ScriptPath: 'powershell_test.ps1'
    azurePowerShellVersion: 'LatestVersion'
