# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


pool:
  vmImage: ubuntu-latest

variables:
  - template: ./build_params.yml

steps:
- script: echo ${{ variables.Hello}}
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: Build an image
  inputs:
    command: buildAndPush
    containerRegistry: 'RomanStephanContainer'
    repository: testrepo
    tags: python-docker

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: container-test'
  inputs:
    azureSubscription: '28e9788f-ff87-400b-ab4e-00b0f896438a'
    appType: webAppContainer
    WebAppName: 'RomanStephanAppVeel'
    DockerNamespace: 'romanstephancontainer.azurecr.io'
    DockerRepository: testrepo
    DockerImageTag: 'python-docker'