# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main


pool:
  vmImage: ubuntu-latest

variables:
  - template: ./build_params.yml

steps:
- script: echo ${{ variables.Hello}}
  displayName: 'Run a one-line script'

- task: Docker@2
  displayName: Build an image
  inputs:
    command: buildAndPush
    containerRegistry: ${{ variables.dockerRegistryServiceConnection }}
    repository: testrepo
    tags: python-docker

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure App Service Deploy: container-test'
  inputs:
    azureSubscription: 'azure_test_1 (5f2578cd-ee3f-4501-b6a6-e9d1ef55b6a9)'
    appType: webAppContainer
    WebAppName: 'container-test'
    DockerNamespace: romanstestcontainerregistry.azurecr.io
    DockerRepository: testrepo
    DockerImageTag: 'python-docker'